[package]
name = "martinez-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
robust-predicates = "0.1.4"
criterion = { version = "=0.7.0", optional = true }
geojson = { version = "=0.24.2", optional = true }

[dev-dependencies]
graph_safe_compare = "0.2.1"
test_each_file = "0.3.5"
criterion = { version = "=0.7.0" }
geojson = { version = "=0.24.2" }
rand = "0.9.2"

[features]
bench = ["criterion", "geojson"]
no_splay_tree = []

[[bench]]
name = "hole_hole"
harness = false

[[bench]]
name = "asia_union"
harness = false

[[bench]]
name = "states_source"
harness = false